

- name: Revoking SSH access
  authorized_key:
    user: "{{ user_name }}"
    state: absent
    key: "{{ lookup('file', '/tmp/{{ user_name }}/id_rsa.pub') }}"
  tags:
    - revoke

- name: User deletion
  user:
    name: "{{ user_name }}"
    state: absent
    remove: yes
  tags:
   - remove
