- name: Add a new user
  user:
    name: "{{ user_name }}"
    password: pass@123
    shell: /bin/bash
  tags:
    - add


- name: Give SSH access
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', '/tmp/{{ user_name }}/id_rsa.pub') }}"
  tags:
    - grant
